name: 'Spamtoberfest | Pull request spam checker'
description: 'List, flag and close pull requests from spammers'
author: 'Maxime Lafarie'
branding:
  icon: 'user-x'
  color: 'gray-dark'

inputs:
  action-type:
    description: 'Type of action to do if spammer is in the spammers list. Possible values: flag | close'
    required: false
    default: 'flag'
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true

runs:
  using: node20
  main: dist/index.js